return {
  'akinsho/bufferline.nvim',
  version = '*',
  dependencies = { 'nvim-tree/nvim-web-devicons' },
  event = 'VeryLazy',
  opts = {
    options = {
      mode = 'buffers',
      numbers = 'none',
      close_command = 'bdelete! %d',
      indicator = { style = 'icon', icon = '▎' },
      buffer_close_icon = '󰅖',
      modified_icon = '●',
      close_icon = '',
      left_trunc_marker = '',
      right_trunc_marker = '',
      max_name_length = 18,
      max_prefix_length = 15,
      truncate_names = true,
      tab_size = 18,
      diagnostics = 'nvim_lsp',
      diagnostics_update_in_insert = false,
      -- Offset for file explorer sidebars
      offsets = {
        {
          filetype = 'neo-tree',
          text = 'File Explorer',
          highlight = 'Directory',
          separator = true,
        },
        {
          filetype = 'snacks_picker_list',
          text = 'Explorer',
          highlight = 'Directory',
          separator = true,
        },
      },
      show_buffer_icons = true,
      show_buffer_close_icons = true,
      show_close_icon = false,
      show_tab_indicators = true,
      separator_style = 'thin',
      always_show_bufferline = true,
      hover = { enabled = true, delay = 200, reveal = { 'close' } },
    },
  },
  keys = {
    { '<S-h>', '<cmd>BufferLineCyclePrev<cr>', desc = 'Prev buffer' },
    { '<S-l>', '<cmd>BufferLineCycleNext<cr>', desc = 'Next buffer' },
    { '<leader>bp', '<cmd>BufferLineTogglePin<cr>', desc = 'Pin buffer' },
    { '<leader>bP', '<cmd>BufferLineGroupClose ungrouped<cr>', desc = 'Close unpinned' },
    { '<leader>bo', '<cmd>BufferLineCloseOthers<cr>', desc = 'Close others' },
    { '<leader>bl', '<cmd>BufferLineCloseRight<cr>', desc = 'Close right' },
    { '<leader>bh', '<cmd>BufferLineCloseLeft<cr>', desc = 'Close left' },
  },
}
